---
- hosts: localhost
  connection: local
  vars:
    user: "serafim"
  environment:
    http_proxy: http://user:password@server:port
    https_proxy: http://user:password@server:port
  user: "{{ user }}" 
  roles:
    - fedora
    - gnome
    - { role: cmprescott.chrome, become: yes }
    - dropbox
    - vim
    - wine
    - zsh
    - tmux
    - python
    - nodejs
    - dotfiles
    - games
