---
- name: install third party software repositories
  dnf:
    name:
      - fedora-workstation-repositories
    state: present
  become: True

- name: enable nvidia repository
  command: dnf config-manager --set-enabled rpmfusion-nonfree-nvidia-driver
  become: True

# https://rpmfusion.org/Howto/NVIDIA?highlight=%28CategoryHowto%29
# wayland is disabled by default: see /etc/gdm/custom.conf
- name: install nvidia drivers
  dnf:
    name:
      - xorg-x11-drv-nvidia
      - akmod-nvidia
      - vulkan
      - xorg-x11-drv-nvidia-libs.i686
      - vdpauinfo
      - libva-vdpau-driver
      - libva-utils
    state: present
  become: True

- name: Add Flathub repository for flatpak
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  become: True

- name: Install Steam flatpak app
  command: flatpak install -y flathub com.valvesoftware.Steam

- name: Install Discord flatpak app
  command: flatpak install -y flathub com.discordapp.Discord
