---
- name: upgrade fedora
  dnf:
    name: "*"
    state: latest
  become: True

- name: install fedora packages
  dnf:
    name:
      - git
      - libselinux-python # needed for some ansible roles
      - powerline
      - the_silver_searcher
      - fzf # https://src.fedoraproject.org/rpms/fzf
      - tldr # https://github.com/tldr-pages/tldr-python-client
    state: present
  become: True
