---
- name: upgrade fedora
  dnf:
    name: "*"
    state: latest
  become: True

- name: install fedora packages
  dnf:
    name:
      - git
      - libselinux-python # needed for some ansible roles
      - the_silver_searcher
      - fzf # https://src.fedoraproject.org/rpms/fzf
      - tldr # https://github.com/tldr-pages/tldr-python-client
      - i3
      - i3status
      - dmenu
      - i3lock
      - xbacklight # change screen brightness
      - feh # image viewer and cataloguer
      - sxhkd # simple X hotkey daemon
    state: present
  become: True
