---
- name: upgrade fedora
  dnf:
    name: "*"
    state: latest
  become: True

- name: install fedora packages
  dnf:
    name:
      - git
      - gnome-tweak-tool
      - libselinux-python # needed for some ansible roles
      - powerline
    state: present
  become: True
