---
- name: symlink dot files in files folder
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: ~/{{ item }}
    state: link
  with_items:
    - .aliases
    - .exports
    - .extras
    - .functions
    - .gitignore
    - .gitconfig
    - .zshrc
    - .vimrc
    - .tmux.conf
    - .tern-project
    - .stylelintrc.json
