---
- name: symlink dot files in files folder
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: ~/{{ item }}
    state: link
  with_items:
    - .gitignore
    - .gitconfig
    - .zshrc
    - .zshenv
      #- .vimrc
