---
- name: make sure folders exist
  file:
    path: ~/{{ item }}
    state: directory
  with_items:
    - .config
    - .config/i3
    - .config/i3blocks
    - .config/termite
    - .config/sxhkd
    - .local/bin

- name: symlink dot files in files folder
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: ~/{{ item }}
    state: link
  with_items:
    - .aliases
    - .exports
    - .extras
    - .functions
    - .gitignore
    - .gitconfig
    - .profile
    - .zshrc
    - .vimrc
    - .tmux.conf
    - .tern-project
    - .stylelintrc.json
    - .config/i3/config
    - .config/i3blocks/config
    - .config/termite/config
    - .config/sxhkd/sxhkdrc

- name: symlink scripts in .local/bin
  file:
    src: "{{ role_path }}/files/scripts/{{ item }}"
    dest: ~/.local/bin/{{ item }}
    state: link
  with_items:
    - teste
