---
- name: install nodejs
  dnf:
    name:
      - nodejs
    state: present
  become: True

- name: create directory for global installations
  file:
    path: "{{ npm_global_dir }}"
    state: directory

- name: install global packages
  npm:
    name: "{{ item }}"
    global: yes
    state: present
  with_items:
    - prettier
    - stylelint # css linter
    - stylelint-config-standard
    - git-open
    - grunt
  environment:
    NPM_CONFIG_PREFIX: "{{ npm_global_dir }}"
  become: False
