#!/usr/bin/env bash
# uses scrot, imagemagick, and i3lock to take a screenshot of the desktop,
# blur it, set that picture as background lock, and lock the desktop

icon="$HOME/.local/bin/locker-icon.png"
tmpbg='/tmp/lock-screen.png'

scrot "$tmpbg"
convert "$tmpbg" -scale 10% -scale 1000% "$tmpbg"
convert "$tmpbg" "$icon" -gravity center -geometry +960 -composite -matte "$tmpbg"
convert "$tmpbg" "$icon" -gravity center -geometry -960 -composite -matte "$tmpbg"
i3lock --show-failed-attempts --ignore-empty-password --image="$tmpbg"
rm "$tmpbg"
