#!/bin/sh
# Inspired by Luke Smith volume script
# https://github.com/LukeSmithxyz/voidrice/blob/e4b3052965d52c97d527f7992a4c0f89e7d3f938/.local/bin/statusbar/volume

# if there is a 2nd argument, store it in NUMBER
# otherwise, NUMBER = 5
NUMBER="${2:-5}"

toggle() { amixer sset Master toggle ;}
mute() { amixer sset Master mute ;}
up() { amixer set Master "$NUMBER"%+ ;}
down() { amixer sset Master "$NUMBER"%- ;}

case "$1" in
    toggle) toggle ;;
    mute) mute ;;
    up) up ;;
    down) down ;;
esac >/dev/null

# Get amixer status
volstat="$(amixer get Master)"

# If Master control is off, print mute symbol and exit
echo "$volstat" | grep "\[off\]" >/dev/null && printf "🔇\\n" && exit

# Otherwise, get volume
vol=$(echo "$volstat" | grep -o "\[[0-9]\+%\]" | sed "s/[^0-9]*//g;1q")

if [ "$vol" -gt "70" ]; then
	icon="🔊"
elif [ "$vol" -lt "30" ]; then
	icon="🔈"
else
	icon="🔉"
fi

printf "%s %s%%\\n" "$icon" "$vol"
