---
- name: install zsh
  dnf:
    name: 
      - zsh
      - git
      - powerline
    state: present
  become: True

- name: clone zplugin
  git:
    repo: https://github.com/zdharma/zplugin.git
    dest: ~/.zplugin/bin
    update: yes

- name: change user shell
  user:
    name: "{{ user }}"
    shell: /bin/zsh
  become: True
