---
- name: install zsh
  dnf:
    name:
      - zsh
      - git
    state: present
  become: True

- name: make sure antigen folder exists
  file:
    path: ~/.antigen
    mode: 0700
    state: directory

- name: install antigen
  uri:
    url: http://git.io/antigen
    dest: ~/.antigen/antigen.zsh
    follow_redirects: safe

- name: change user shell
  user:
    name: "{{ user }}"
    shell: /bin/zsh
  become: True
