---
- name: install gnome extensions
  dnf:
    name:
      - chrome-gnome-shell
      - gnome-tweak-tool
      - gnome-shell-extension-topicons-plus
      - gnome-shell-extension-openweather
    state: present
  become: True

- name: install theme related packages
  dnf:
    name:
      - arc-theme
  become: True

- name: add papirus icon repository
  command: dnf copr enable -y dirkdavidis/papirus-icon-theme
  become: True

- name: install papirus icon theme
  dnf:
    name:
      - papirus-icon-theme
  become: True
