---
- name: install tilix
  dnf:
    name: tilix
    state: latest
  become: True

- name: Create themes folder
  file:
    path: ~/.config/tilix/schemes
    mode: 0700
    state: directory

- name: Download themes
  get_url:
    url: "https://raw.githubusercontent.com/storm119/Tilix-Themes/master/Themes/{{ item }}.json"
    dest: ~/.config/tilix/schemes/{{ item }}.json
    mode: 0666
  with_items:
    - frontend-galaxy
    - one-dark
