---
- name: install dnf plugins
  dnf:
    name:
      - dnf-plugins-core
    state: present
  become: True

- name: add docker repository
  command: dnf config-manager --add-repo=https://download.docker.com/linux/fedora/docker-ce.repo
  become: True

- name: install docker-ce
  dnf:
    name:
      - docker-ce
    state: present
  become: True

- name: enable and start service
  systemd:
    name: docker
    enabled: yes
    state: started
    daemon_reload: yes
  become: True
